delete:
	- kubectl delete -k ./deployments/src-origin-07-enp33s0.3911
	- kubectl delete -k ./deployments/src-origin-07-enp33s0.3912
	- kubectl delete -k ./deployments/src-origin-man239-p1p1
	- kubectl delete -k ./deployments/src-origin-man239-p4p2
create:
	- kubectl apply -k ./deployments/src-origin-07-enp33s0.3911
	- kubectl apply -k ./deployments/src-origin-07-enp33s0.3912
	- kubectl apply -k ./deployments/src-origin-man239-p1p1
	- kubectl apply -k ./deployments/src-origin-man239-p4p2
