resources:
  - deploy.yaml

configMapGenerator:
  - name: NAME_PLACEHOLDER-conf
    files:
      - xrootd-third-party-copy.cfg
      - auth-file-noauth
      - mkfile.sh
  - name: xrootd-server-supervisor
    files:
      - supervisord.conf

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app: NAME_PLACEHOLDER
