apiVersion: apps/v1
kind: Deployment
metadata:
  name: xrootd-redi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xrootd-redi
  template:
    metadata:
      labels:
        app: xrootd-redi
    spec:
      containers:
      - name: mypod
        image: ddavila0/xrootd-scale-tests-server:fresh
        #imagePullPolicy: Always
        #lifecycle:
        #  postStart:
        #    exec:
        #      command: ["/bin/sh", "-c", "head -c 1M /dev/urandom >/data/store/1MB_01; head -c 1M /dev/urandom >/data/store/1MB_02;"]
        ports:
         - containerPort: 2040
           hostPort: 2040
         - containerPort: 1094
           hostPort: 1094
        volumeMounts:
        - name: auth-file
          mountPath: /etc/xrootd/auth-file-noauth
          subPath: auth-file-noauth
        - name: xrootd-config
          mountPath: /etc/xrootd/xrootd-redi.cfg
          subPath: xrootd-redi.cfg
        - name: cmsd-config
          mountPath: /etc/xrootd/cmsd-redi.cfg
          subPath: cmsd-redi.cfg
        resources:
          limits:
            cpu: 16
            memory: 32Gi
          requests:
            cpu: 16
            memory: 32Gi
      restartPolicy: Always
      volumes:
      - name : auth-file
        configMap:
           defaultMode: 420
           items:
           - key: auth-file-noauth
             path: auth-file-noauth
           name: xrootd-config-redi
      - name : xrootd-config
        configMap:
           defaultMode: 420
           items:
           - key: xrootd-redi.cfg
             path: xrootd-redi.cfg
           name: xrootd-config-redi
      - name : cmsd-config
        configMap:
           defaultMode: 420
           items:
           - key: cmsd-redi.cfg
             path: cmsd-redi.cfg
           name: xrootd-config-redi
