apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: tpc-master
  name: tpc-master
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: tpc-master
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: tpc-master
    spec:
      containers:
      - image: aaarora/tpc-master-xrootd:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        name: tpc-master
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "osg-ca-generator --host -e 365"]
        env:
        - name: OSG_FQDN
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          limits:
            cpu: 15
            memory: 10Gi
          requests:
            cpu: 14
            memory: 8Gi
        volumeMounts:
        - mountPath: /home/tpc.py
          name: tpc-script
          subPath: tpc.py
        - mountPath: /home/tpc_multi.py
          name: tpc-script
          subPath: tpc_multi.py
        - mountPath: /etc/pki/CA/private/OSG-Test-CA.key
          name: ca
          subPath: OSG-Test-CA.pem
        - mountPath: /usr/lib/python2.7/site-packages/cagen.py
          name: cagen
          subPath: cagen.py
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cache-vol
        emptyDir: {}
      - name: tpc-script
        configMap: 
          name: tpc-script
          items:
          - key: tpc.py
            path: tpc.py
          - key: tpc_multi.py
            path: tpc_multi.py
          defaultMode: 0777
      - name: ca
        secret:
          secretName: https-self-certs
          items:
          - key: OSG-Test-CA.pem
            path: OSG-Test-CA.pem
          defaultMode: 0644
      - name: cagen
        configMap:
          name: cert-script
