apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: tpc-master
  name: tpc-master
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: tpc-master
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: tpc-master
    spec:
      tolerations:
      - key: "nautilus.io/nsi"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - image: aaarora/tpc-master-xrootd:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2096
        name: tpc-master
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "osg-ca-generator --host -e 365"]
        env:
        - name: OSG_FQDN
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          limits:
            cpu: 11
            memory: 10Gi
          requests:
            cpu: 10
            memory: 6Gi
        volumeMounts:
        - mountPath: /etc/pki/CA/private/OSG-Test-CA.key
          name: ca
          subPath: OSG-Test-CA.pem
      dnsPolicy: Default # TODO: check this?
      restartPolicy: Always
      schedulerName: default-scheduler
      nodeSelector:
        kubernetes.io/hostname: k8s-gen4-07.ultralight.org
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cache-vol
        emptyDir: {}
      - name: ca
        secret:
          secretName: https-self-certs
          items:
          - key: OSG-Test-CA.pem
            path: OSG-Test-CA.pem
          defaultMode: 0644
