apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: tpc-master
  name: tpc-master
  namespace: osg-gil
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: tpc-master
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: tpc-master
    spec:
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/stashcache
        operator: Exists
      containers:
      - image: aaarora/tpc-master:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        name: tpc-master
        env:
        - name: TIMEFORMAT
          value: "%3R"
        - name: OSG_FQDN
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi
        volumeMounts:
        - mountPath: /home/tpc.py
          name: tpc-script
          subPath: tpc.py
          readOnly: false 
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: stashcache.t2.ucsd.edu
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cache-vol
        emptyDir: {}
      - name: tpc-script
        configMap: 
          name: tpc-script
          items:
          - key: tpc.py
            path: tpc.py
          defaultMode: 0777
