delete:
	- kubectl delete -k ./deployments/dst-origin-01-enp1s0f0
	- kubectl delete -k ./deployments/dst-origin-01-enp1s0f1
	- kubectl delete -k ./deployments/dst-origin-01-enp33s0f0
	- kubectl delete -k ./deployments/dst-origin-01-enp33s1f0
	- kubectl delete -k ./deployments/dst-origin-02-enp1s0f0
	- kubectl delete -k ./deployments/dst-origin-02-enp1s0f1
	- kubectl delete -k ./deployments/dst-origin-02-enp33s0f0
	- kubectl delete -k ./deployments/dst-origin-02-enp33s1f0
create:
	- kubectl apply -k ./deployments/dst-origin-01-enp1s0f0
	- kubectl apply -k ./deployments/dst-origin-01-enp1s0f1
	- kubectl apply -k ./deployments/dst-origin-01-enp33s0f0
	- kubectl apply -k ./deployments/dst-origin-01-enp33s1f0
	- kubectl apply -k ./deployments/dst-origin-02-enp1s0f0
	- kubectl apply -k ./deployments/dst-origin-02-enp1s0f1
	- kubectl apply -k ./deployments/dst-origin-02-enp33s0f0
	- kubectl apply -k ./deployments/dst-origin-02-enp33s1f0
