apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: xrootd-pvc
    namespace: osg-gil
spec:
    accessModes:
      - ReadWriteMany
    storageClassName: rook-cephfs
    resources:
      requests:
        storage: 1Gi
